### transforming code in to application
 - replace traditional index manipulation with python core idiomatic


In [1]:
# looping over a range of numbers - traditional approach
for i in [0,1,2,3,4,5]:
    print(i*2,end=" ")

0 2 4 6 8 10 

In [2]:
#idiomatic programming
for i in range (6):
    print(i**2,end=" ")

0 1 4 9 16 25 

### looping over a collection

In [6]:
colours=['red','greeen','yellow','purple']
for i in range(len(colours)):
    print(colours[i],end=" ")

red greeen yellow purple 

In [7]:
for colour in colours:
    print(colour,end=" ")

red greeen yellow purple 

### looping backwards

In [8]:
colours=['red','greeen','yellow','purple']
for i in range(len(colours)-1,-1,-1):
    print(colours[i],end=" ")

purple yellow greeen red 

In [9]:
for colour in reversed(colours):
    print(colour,end=" ")

purple yellow greeen red 

In [11]:
colours=['red','greeen','yellow','purple']
for colours in sorted(colours,reverse=True):
     print(colours,end=" ")

yellow red purple greeen 

###
  - if x<=y and y<=z:
  - if x<=y<=z:
  - if x= True
  - if x
 
  

### pandas

In [7]:
import pandas as pd

In [8]:
dt={'ID':[11,12,13,14,15],
    'first_name':['A','B','C','D','E'],
    'company':['aa','bb','cc','dd','ee'],
    'address':['hyd','hyd','hyd','hyd','hyd']}
mydt = pd.DataFrame(dt)

In [9]:
print(mydt)

   ID first_name company address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [10]:
import os

In [ ]:
os.chdir("pathfile")#saves to certain location

In [11]:
mydt.to_csv('workingfile.csv',index=False)


### reading the data from csv file

In [12]:
mydata = pd.read_csv('workingfile.csv')

In [15]:
print(mydata)

   ID first_name company address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [14]:
mydata1 = pd.read_csv('workingfile.csv',skiprows=1,names=["CustId","Name","Company","Address"])

In [16]:
print(mydata1)

   CustId Name Company Address
0      11    A      aa     hyd
1      12    B      bb     hyd
2      13    C      cc     hyd
3      14    D      dd     hyd
4      15    E      ee     hyd


In [17]:
pwd


'C:\\Users\\229'

###  Print on ly two numbers
### print large value from custid column-max
### print least value from custid column-min
### average value of custid column-sum(li)/len(li)    

# Numpy-working with Multi-Dimensional Array
 - numpy arrays is a bit like Python List
 - Numpy array is data structure of Numpy Lib
 - It's short name for Numeric

In [1]:
import numpy as np # i mport numpy pacakage

In [2]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [4]:
array=np.array(li)
print(array)

[1 2 3 4 5]


In [5]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [6]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [8]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [ ]:
om turtle import*
pencolor('red')
for x in range (100):
   t.forward(x)
   t.left(90)
